### ISSUE TITLE
🪲 mobile accessibility

### ISSUE THREAD

**Issue by straight-code** [straight-code/web3-shop#4]
Make components accessible & reusable.
- [x] Safari
- [x] Chrome
- [x] Android

**Comment by straight-code** [comment]
`Notes:`  `[
create reusable/accessible components ]`

`NEEDED:` 

`[ "name": "header.css",]`
`["name": "PriceRanges.css",]`
`["name": "Results.css",]`
`["name": "home.css",]`
`["name": "product.css",]`
`["name": "App.css",]`

**Comment by RwondazTheGreat** [comment]
- [✅] header.css
- [✅] Results.css
- [✅] Home.css
- [✅] Product.css
- [✅] App.css
- [✅] PriceRanges.css

`Current Version : v2.0.7-development`
`Home:`
![image](https://user-images.githubusercontent.com/98624656/182990643-ab737dbe-31cf-4b86-a98d-dbc136066628.jpeg)
`Categories:`
![image](https://user-images.githubusercontent.com/98624656/182990771-eb9c572c-5b39-421f-84bd-a7dfaab72b7d.jpeg)
`Product:`
![image](https://user-images.githubusercontent.com/98624656/182991112-3d274b97-0d31-47a4-a218-7a573e09fbe3.jpeg)

`v2.0.8`

`Home:`
![image](https://user-images.githubusercontent.com/98624656/183222303-02997c84-429e-4cc2-8077-0363fff91cf4.jpeg)

`Categories:`
![image](https://user-images.githubusercontent.com/98624656/183222313-eb84eb67-0af9-4079-87df-c6d230d2ee1e.jpeg)

`Product:`
![image](https://user-images.githubusercontent.com/98624656/183222326-69ff4f22-96df-4d45-8882-6f1f707f2787.jpeg)


Note💭: few sizing bugs must, and new ad content needed more mobile friendly

**Comment by straight-code** [comment]
`v2.0.9` : 

`home:`
![image](https://user-images.githubusercontent.com/97550737/183230113-fc22dc2b-f14e-4896-aa95-106e5a742691.jpeg)
`categories`
![image](https://user-images.githubusercontent.com/97550737/183230119-8aaa46cb-c765-4215-be98-905fcd1b480a.jpeg)
`product`
![image](https://user-images.githubusercontent.com/97550737/183230123-18ce2733-c41d-4653-847a-401d02905b3a.jpeg)

Note💭: resize of product card still needed & purchase card resize back to 250px

**Comment by straight-code** [comment]
issue on ios devices
